target:src/server/simple_telnet_serv.c src/client/simple_telnet_cli.c
	gcc -o bin/simpl_telnet_serv -Iinclude src/server/simple_telnet_serv.c
	gcc -o bin/simpl_telnet_cli -Iinclude src/client/simple_telnet_cli.c

clean:
	rm -rf bin/*
